import { PrismaClient, TicketStatus, TicketCategory } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const tickets: {
  subject: string;
  body: string;
  status: TicketStatus;
  category: TicketCategory | null;
  senderName: string;
  senderEmail: string;
  createdAt: Date;
}[] = [
  // --- BILLING (20 tickets) ---
  { subject: "Double charged for monthly subscription", body: "I was charged twice on my credit card for the June billing cycle. Transaction IDs: TXN-8821 and TXN-8822.", status: "open", category: "billing", senderName: "Rachel Kim", senderEmail: "rachel.kim@outlook.com", createdAt: new Date("2026-07-05T09:15:00Z") },
  { subject: "Need invoice for Q2 2026", body: "Our accounting department requires a consolidated invoice for April–June 2026. Can you send a PDF?", status: "pending", category: "billing", senderName: "Marcus Thompson", senderEmail: "m.thompson@acmecorp.com", createdAt: new Date("2026-07-04T14:30:00Z") },
  { subject: "Upgrade from Starter to Pro plan", body: "I'd like to upgrade my account to the Pro plan. Can you process this mid-cycle and prorate?", status: "resolved", category: "billing", senderName: "Sofia Patel", senderEmail: "sofia.p@gmail.com", createdAt: new Date("2026-07-03T11:00:00Z") },
  { subject: "Refund request – cancelled within 24 hours", body: "I signed up yesterday but realized the product doesn't fit our needs. Requesting a full refund per your policy.", status: "open", category: "billing", senderName: "Daniel Garcia", senderEmail: "dgarcia@lawfirm.co", createdAt: new Date("2026-07-05T07:45:00Z") },
  { subject: "Tax exemption certificate upload", body: "We are a 501(c)(3) nonprofit. Attaching our tax exemption certificate. Please apply it to our account.", status: "pending", category: "billing", senderName: "Aisha Johnson", senderEmail: "aisha@helpinghands.org", createdAt: new Date("2026-07-02T16:20:00Z") },
  { subject: "Payment failed – card expired", body: "My payment failed because my card expired. I've updated it in the portal but the retry isn't working.", status: "open", category: "billing", senderName: "Liam O'Brien", senderEmail: "liam.obrien@fastmail.com", createdAt: new Date("2026-07-05T06:10:00Z") },
  { subject: "Enterprise pricing inquiry for 500+ seats", body: "We're evaluating your platform for our organization (~500 users). Can we schedule a call to discuss enterprise pricing?", status: "pending", category: "billing", senderName: "Yuki Tanaka", senderEmail: "ytanaka@megabank.jp", createdAt: new Date("2026-07-01T10:00:00Z") },
  { subject: "Charge appearing as unknown merchant", body: "The charge on my bank statement shows as 'STRIPE* UNKNOWN' instead of your company name. Is this legitimate?", status: "resolved", category: "billing", senderName: "Emma Wilson", senderEmail: "emma.w@protonmail.com", createdAt: new Date("2026-06-30T13:45:00Z") },
  { subject: "Cancel auto-renewal", body: "Please cancel auto-renewal on my annual plan. I want to keep access until the current period ends on Aug 15.", status: "closed", category: "billing", senderName: "Carlos Rivera", senderEmail: "crivera@smallbiz.com", createdAt: new Date("2026-06-28T09:30:00Z") },
  { subject: "Apply coupon code SUMMER26", body: "I forgot to apply the coupon code SUMMER26 at checkout. Can it be applied retroactively?", status: "resolved", category: "billing", senderName: "Priya Sharma", senderEmail: "priya.sharma@techstart.io", createdAt: new Date("2026-06-29T15:00:00Z") },
  { subject: "Billing address change", body: "We've moved offices. Please update our billing address to 450 Innovation Blvd, Austin TX 78701.", status: "closed", category: "billing", senderName: "Mike Chen", senderEmail: "mchen@designstudio.com", createdAt: new Date("2026-06-25T11:20:00Z") },
  { subject: "Dispute: charged after cancellation", body: "I cancelled my account on June 1st but was still charged on July 1st. Please reverse this charge immediately.", status: "open", category: "billing", senderName: "Fatima Al-Hassan", senderEmail: "fatima.ah@email.com", createdAt: new Date("2026-07-04T08:00:00Z") },
  { subject: "Switch from annual to monthly billing", body: "Can I switch from annual to monthly billing when my current term ends? I'd like more flexibility.", status: "pending", category: "billing", senderName: "James Walker", senderEmail: "jwalker@freelance.dev", createdAt: new Date("2026-07-03T17:30:00Z") },
  { subject: "VAT number not reflecting on invoices", body: "I added our EU VAT number (DE123456789) two months ago but invoices still don't show it.", status: "open", category: "billing", senderName: "Anna Müller", senderEmail: "anna.mueller@berlintech.de", createdAt: new Date("2026-07-04T10:15:00Z") },
  { subject: "Requesting payment via wire transfer", body: "Our company policy doesn't allow credit card payments. Can we pay via bank wire transfer instead?", status: "pending", category: "billing", senderName: "Robert Nguyen", senderEmail: "rnguyen@govcontractor.com", createdAt: new Date("2026-07-02T14:00:00Z") },
  { subject: "Student discount verification", body: "I'm a full-time CS student at MIT. Do you offer student discounts? I can provide my .edu email for verification.", status: "resolved", category: "billing", senderName: "Zoe Martinez", senderEmail: "zmartinez@mit.edu", createdAt: new Date("2026-06-27T09:00:00Z") },
  { subject: "Unexpected price increase", body: "My monthly bill went from $29 to $49 without any notification. Was there a pricing change I missed?", status: "open", category: "billing", senderName: "David Park", senderEmail: "dpark@startup.co", createdAt: new Date("2026-07-05T11:30:00Z") },
  { subject: "Add second payment method as backup", body: "Can I add a second credit card as a fallback payment method in case the primary one fails?", status: "closed", category: "billing", senderName: "Lisa Brown", senderEmail: "lisa.brown@yahoo.com", createdAt: new Date("2026-06-26T16:45:00Z") },
  { subject: "Currency conversion fee complaint", body: "I'm being charged in USD but my bank adds a 3% conversion fee. Do you support billing in EUR?", status: "pending", category: "billing", senderName: "Henrik Larsson", senderEmail: "henrik@stockholmdesign.se", createdAt: new Date("2026-07-01T12:00:00Z") },
  { subject: "Duplicate subscription detected", body: "I appear to have two active subscriptions under the same email. One was created by mistake during signup.", status: "open", category: "billing", senderName: "Olivia Taylor", senderEmail: "olivia.t@icloud.com", createdAt: new Date("2026-07-04T15:20:00Z") },

  // --- TECHNICAL (20 tickets) ---
  { subject: "API returning 502 errors intermittently", body: "Our integration is getting 502 Bad Gateway responses about 30% of the time since yesterday morning.", status: "open", category: "technical", senderName: "Kevin Zhang", senderEmail: "kzhang@devteam.io", createdAt: new Date("2026-07-05T08:00:00Z") },
  { subject: "SSO login failing with SAML assertion error", body: "Our Okta SSO integration stopped working. Error: 'Invalid SAML assertion: audience mismatch'. Nothing changed on our end.", status: "open", category: "technical", senderName: "Sarah Mitchell", senderEmail: "s.mitchell@enterprise.com", createdAt: new Date("2026-07-05T07:30:00Z") },
  { subject: "Webhook deliveries delayed by 10+ minutes", body: "Webhook events that used to arrive instantly are now delayed by 10–15 minutes. Affecting our real-time dashboard.", status: "pending", category: "technical", senderName: "Alex Petrov", senderEmail: "alex.p@dataflow.io", createdAt: new Date("2026-07-04T16:00:00Z") },
  { subject: "CSV export truncated at 10,000 rows", body: "When I export my data as CSV, it stops at exactly 10,000 rows. I have 45,000 records. Is there a limit?", status: "resolved", category: "technical", senderName: "Maria Santos", senderEmail: "msantos@analytics.co", createdAt: new Date("2026-07-03T13:15:00Z") },
  { subject: "Mobile app crashes on iOS 19 after latest update", body: "After updating your app to v4.2.1, it crashes immediately on launch on my iPhone 16 running iOS 19.", status: "open", category: "technical", senderName: "Tom Anderson", senderEmail: "tanderson@gmail.com", createdAt: new Date("2026-07-05T10:45:00Z") },
  { subject: "Two-factor authentication codes not arriving", body: "I'm not receiving SMS 2FA codes. My phone number is correct. I've tried 5 times in the last hour.", status: "open", category: "technical", senderName: "Nina Kowalski", senderEmail: "nina.k@securecorp.pl", createdAt: new Date("2026-07-05T06:30:00Z") },
  { subject: "Dashboard loading extremely slowly (30+ seconds)", body: "The main dashboard takes over 30 seconds to load. Other pages are fine. Started about 2 days ago.", status: "pending", category: "technical", senderName: "Chris Lee", senderEmail: "clee@performanceteam.com", createdAt: new Date("2026-07-04T11:00:00Z") },
  { subject: "File upload fails for files over 25MB", body: "I get a generic 'Upload failed' error when trying to upload files larger than 25MB. Your docs say the limit is 100MB.", status: "resolved", category: "technical", senderName: "Raj Patel", senderEmail: "raj@cloudmedia.in", createdAt: new Date("2026-07-02T09:45:00Z") },
  { subject: "Search returning zero results for known items", body: "Searching for items by name returns nothing, even though I can see them when browsing manually. Search seems broken.", status: "open", category: "technical", senderName: "Julia Fernandez", senderEmail: "jfernandez@retailchain.com", createdAt: new Date("2026-07-04T14:20:00Z") },
  { subject: "Email notifications going to spam folder", body: "All notification emails from your platform are landing in our spam folder in Google Workspace. Started last week.", status: "pending", category: "technical", senderName: "Ben Clarke", senderEmail: "bclarke@agency.uk", createdAt: new Date("2026-07-03T10:30:00Z") },
  { subject: "Cannot connect custom domain – DNS verification stuck", body: "I've added the CNAME and TXT records as instructed but domain verification has been 'pending' for 48 hours.", status: "pending", category: "technical", senderName: "Hannah Kim", senderEmail: "hannah@mybrand.store", createdAt: new Date("2026-07-03T08:00:00Z") },
  { subject: "GraphQL endpoint returning deprecated field warnings", body: "Our queries are returning deprecation warnings for fields we still rely on. When will these be removed?", status: "resolved", category: "technical", senderName: "Owen Murphy", senderEmail: "omurphy@graphqlshop.dev", createdAt: new Date("2026-07-01T15:30:00Z") },
  { subject: "Rate limiting hitting us during normal usage", body: "We're getting 429 Too Many Requests errors with only ~50 req/min, well under your documented 200 req/min limit.", status: "open", category: "technical", senderName: "Alicia Gomez", senderEmail: "agomez@integrations.io", createdAt: new Date("2026-07-04T12:00:00Z") },
  { subject: "Timezone display incorrect in reports", body: "All report timestamps show in UTC despite my account being set to America/New_York. This is causing confusion.", status: "resolved", category: "technical", senderName: "Nathan Brooks", senderEmail: "nbrooks@consulting.com", createdAt: new Date("2026-06-30T17:00:00Z") },
  { subject: "OAuth2 token refresh returning invalid_grant", body: "Our automated system's refresh token stopped working. Error: invalid_grant. Token was issued 3 days ago.", status: "open", category: "technical", senderName: "Ines Dubois", senderEmail: "ines@paristech.fr", createdAt: new Date("2026-07-05T05:00:00Z") },
  { subject: "PDF generation missing images", body: "When generating PDF reports, all embedded images are replaced with broken image icons. HTML preview looks fine.", status: "pending", category: "technical", senderName: "Victor Huang", senderEmail: "vhuang@printservices.com", createdAt: new Date("2026-07-02T13:00:00Z") },
  { subject: "Bulk import failing silently on row 500+", body: "CSV import appears to succeed but only imports the first 500 rows. No error shown. File has 2,000 rows.", status: "open", category: "technical", senderName: "Grace Okafor", senderEmail: "gokafor@nigeriaops.ng", createdAt: new Date("2026-07-04T09:15:00Z") },
  { subject: "Browser back button breaks form state", body: "If I navigate away from a half-filled form and press back, all data is lost. Expected: form state preserved.", status: "closed", category: "technical", senderName: "Paul Martin", senderEmail: "pmartin@uxteam.com", createdAt: new Date("2026-06-28T14:00:00Z") },
  { subject: "REST API v2 migration guide unclear", body: "The v1→v2 migration guide doesn't cover the /users endpoint changes. We're blocked on upgrading.", status: "pending", category: "technical", senderName: "Diana Reyes", senderEmail: "dreyes@migration.dev", createdAt: new Date("2026-07-01T11:45:00Z") },
  { subject: "WebSocket connection drops every 5 minutes", body: "Our real-time connection drops exactly every 5 minutes and reconnects. Happens in all browsers.", status: "open", category: "technical", senderName: "Ian Foster", senderEmail: "ifoster@realtimeapp.com", createdAt: new Date("2026-07-05T04:30:00Z") },

  // --- BUG (20 tickets) ---
  { subject: "Saved filters reset after page refresh", body: "Custom filters I apply to the ticket list disappear when I refresh the page. They should persist.", status: "open", category: "bug", senderName: "Megan White", senderEmail: "mwhite@supportteam.com", createdAt: new Date("2026-07-05T08:30:00Z") },
  { subject: "Notification count badge shows wrong number", body: "The bell icon shows 12 unread notifications but I only have 3 actual unread items.", status: "open", category: "bug", senderName: "Tyler Reed", senderEmail: "treed@startuplab.co", createdAt: new Date("2026-07-05T09:00:00Z") },
  { subject: "Dark mode text invisible on certain pages", body: "In dark mode, the text on the Settings > Profile page is dark gray on dark background — completely unreadable.", status: "pending", category: "bug", senderName: "Amy Chang", senderEmail: "achang@designcrit.com", createdAt: new Date("2026-07-04T13:00:00Z") },
  { subject: "Copy-paste strips formatting in rich text editor", body: "When I paste content from Google Docs, all formatting (bold, lists, links) is stripped. Plain text only comes through.", status: "resolved", category: "bug", senderName: "Jake Sullivan", senderEmail: "jsullivan@contentteam.org", createdAt: new Date("2026-07-03T14:30:00Z") },
  { subject: "Date picker shows wrong month on first click", body: "Opening the date picker always shows January 2020 instead of the current month. Second click fixes it.", status: "open", category: "bug", senderName: "Lily Evans", senderEmail: "levans@qa.team", createdAt: new Date("2026-07-04T10:00:00Z") },
  { subject: "Drag-and-drop reordering saves but reverts on reload", body: "I can drag items to reorder them and it looks like it saves, but refreshing the page reverts to the old order.", status: "open", category: "bug", senderName: "Noah Bennett", senderEmail: "nbennett@projectmgmt.com", createdAt: new Date("2026-07-05T07:00:00Z") },
  { subject: "Email template preview doesn't match actual sent email", body: "The preview in the template editor shows correct formatting but the actual sent email has broken layout in Outlook.", status: "pending", category: "bug", senderName: "Chloe Davis", senderEmail: "cdavis@emailmarketing.co", createdAt: new Date("2026-07-03T16:00:00Z") },
  { subject: "Pagination skips page 2 entirely", body: "Clicking 'Next' from page 1 goes directly to page 3. There's no way to view items on page 2.", status: "open", category: "bug", senderName: "Ethan Moore", senderEmail: "emoore@bugtracker.io", createdAt: new Date("2026-07-04T11:30:00Z") },
  { subject: "Avatar upload accepts file but shows default icon", body: "I uploaded a profile photo and got a success message, but my avatar still shows the default silhouette.", status: "resolved", category: "bug", senderName: "Isabella Torres", senderEmail: "itorres@social.app", createdAt: new Date("2026-07-02T12:00:00Z") },
  { subject: "Keyboard shortcut Ctrl+S triggers browser save dialog", body: "Pressing Ctrl+S to save in the editor opens the browser's Save Page dialog instead of saving the document.", status: "closed", category: "bug", senderName: "Ryan Clark", senderEmail: "rclark@devtools.io", createdAt: new Date("2026-06-29T10:00:00Z") },
  { subject: "Sorting by name puts lowercase entries at the end", body: "When sorting contacts alphabetically, all lowercase names appear after Z. Case-insensitive sort expected.", status: "open", category: "bug", senderName: "Sophia Adams", senderEmail: "sadams@crm.biz", createdAt: new Date("2026-07-04T15:45:00Z") },
  { subject: "Markdown preview renders HTML tags as raw text", body: "Using `<details>` or `<summary>` tags in markdown shows raw HTML instead of rendering collapsible sections.", status: "pending", category: "bug", senderName: "Lucas Wright", senderEmail: "lwright@docs.dev", createdAt: new Date("2026-07-03T09:30:00Z") },
  { subject: "Auto-save creates duplicate drafts", body: "The auto-save feature is creating multiple draft copies of the same document. I now have 15 duplicates.", status: "open", category: "bug", senderName: "Ella Robinson", senderEmail: "erobinson@writer.co", createdAt: new Date("2026-07-05T10:00:00Z") },
  { subject: "Logout doesn't clear session on other tabs", body: "After logging out in one tab, other open tabs still show the dashboard and can make API calls.", status: "open", category: "bug", senderName: "Mason Hill", senderEmail: "mhill@securityaudit.com", createdAt: new Date("2026-07-04T17:00:00Z") },
  { subject: "Decimal values rounded in currency fields", body: "Entering $19.99 in a price field saves as $20.00. All decimal values are being rounded to whole numbers.", status: "open", category: "bug", senderName: "Ava Campbell", senderEmail: "acampbell@ecommerce.shop", createdAt: new Date("2026-07-05T06:00:00Z") },
  { subject: "Multi-select dropdown closes after each selection", body: "The tag multi-select closes its dropdown after picking each tag, requiring me to reopen it every time.", status: "resolved", category: "bug", senderName: "Jack Peterson", senderEmail: "jpeterson@workflow.app", createdAt: new Date("2026-07-01T14:00:00Z") },
  { subject: "Print view cuts off right side of table", body: "When printing reports, the rightmost 2 columns are cut off. Screen view is fine. Happens in Chrome and Firefox.", status: "pending", category: "bug", senderName: "Charlotte Young", senderEmail: "cyoung@printfix.com", createdAt: new Date("2026-07-02T10:30:00Z") },
  { subject: "Password reset link expires in 5 minutes instead of 24h", body: "The password reset email says the link is valid for 24 hours but it expires after about 5 minutes.", status: "open", category: "bug", senderName: "Benjamin Scott", senderEmail: "bscott@usertest.org", createdAt: new Date("2026-07-04T08:45:00Z") },
  { subject: "Chart tooltips show [object Object]", body: "Hovering over data points in the analytics charts shows '[object Object]' instead of the actual values.", status: "open", category: "bug", senderName: "Mia Nelson", senderEmail: "mnelson@dataviz.co", createdAt: new Date("2026-07-05T11:15:00Z") },
  { subject: "Form validation error messages overlap input fields", body: "On mobile, validation error messages overlap the input fields below them, making the form unusable.", status: "pending", category: "bug", senderName: "Alexander King", senderEmail: "aking@mobiletest.dev", createdAt: new Date("2026-07-03T15:00:00Z") },

  // --- FEATURE REQUEST (20 tickets) ---
  { subject: "Add ability to merge duplicate tickets", body: "We often get duplicate tickets from the same customer. Would love the ability to merge them into one.", status: "open", category: "feature_request", senderName: "Rebecca Foster", senderEmail: "rfoster@supportops.com", createdAt: new Date("2026-07-05T08:15:00Z") },
  { subject: "Slack integration for new ticket notifications", body: "We use Slack for internal comms. Would be great to get a Slack notification when a new ticket is created.", status: "open", category: "feature_request", senderName: "Trevor Hayes", senderEmail: "thayes@slackfirst.io", createdAt: new Date("2026-07-04T09:00:00Z") },
  { subject: "Support for custom ticket fields", body: "We need to add custom fields (e.g., 'Product Version', 'Region') to tickets. Currently limited to the defaults.", status: "pending", category: "feature_request", senderName: "Monica Diaz", senderEmail: "mdiaz@customfields.co", createdAt: new Date("2026-07-03T12:00:00Z") },
  { subject: "Dark mode support", body: "Please add a dark mode option. Working late nights and the bright white interface is harsh on the eyes.", status: "closed", category: "feature_request", senderName: "Leo Hoffman", senderEmail: "lhoffman@nightowl.dev", createdAt: new Date("2026-06-15T20:00:00Z") },
  { subject: "Ability to set ticket priority levels", body: "We need Priority (Low/Medium/High/Critical) as a ticket field to help our team triage effectively.", status: "open", category: "feature_request", senderName: "Natalie Ross", senderEmail: "nross@triage.team", createdAt: new Date("2026-07-04T13:30:00Z") },
  { subject: "Bulk actions on ticket list", body: "Need ability to select multiple tickets and perform bulk actions: close, assign, change status, add tags.", status: "open", category: "feature_request", senderName: "Derek Price", senderEmail: "dprice@efficiency.co", createdAt: new Date("2026-07-05T09:45:00Z") },
  { subject: "Customer satisfaction survey after ticket resolution", body: "Automatically send a CSAT survey when a ticket is marked as resolved. We need to measure support quality.", status: "pending", category: "feature_request", senderName: "Victoria Lane", senderEmail: "vlane@customersuccess.io", createdAt: new Date("2026-07-02T11:00:00Z") },
  { subject: "SLA timer and breach alerts", body: "Need SLA tracking with configurable response/resolution times and automatic alerts when SLA is about to breach.", status: "open", category: "feature_request", senderName: "Patrick Murphy", senderEmail: "pmurphy@sla.watch", createdAt: new Date("2026-07-04T07:00:00Z") },
  { subject: "Canned responses / saved reply templates", body: "Our agents type the same responses repeatedly. Saved reply templates would save hours per week.", status: "resolved", category: "feature_request", senderName: "Samantha Cole", senderEmail: "scole@templates.io", createdAt: new Date("2026-06-30T10:00:00Z") },
  { subject: "Allow customers to view ticket status via portal", body: "Customers currently have no visibility into their ticket status. A self-service portal would reduce follow-up emails.", status: "open", category: "feature_request", senderName: "Andre Williams", senderEmail: "awilliams@selfservice.co", createdAt: new Date("2026-07-03T14:00:00Z") },
  { subject: "Internal notes on tickets (not visible to customer)", body: "We need the ability to add internal notes that only agents can see, for collaboration without exposing to the customer.", status: "open", category: "feature_request", senderName: "Katie Morgan", senderEmail: "kmorgan@teamcollab.com", createdAt: new Date("2026-07-04T16:30:00Z") },
  { subject: "Ticket assignment rules / auto-routing", body: "Auto-assign tickets based on category: billing → finance team, technical → engineering, etc.", status: "pending", category: "feature_request", senderName: "Simon Cooper", senderEmail: "scooper@routing.biz", createdAt: new Date("2026-07-01T13:00:00Z") },
  { subject: "Export tickets to PDF", body: "Need to export individual tickets (with full conversation history) as PDF for legal/compliance archiving.", status: "open", category: "feature_request", senderName: "Lauren Bell", senderEmail: "lbell@compliance.legal", createdAt: new Date("2026-07-03T10:00:00Z") },
  { subject: "Multi-language support for customer-facing emails", body: "We serve customers in 8 countries. Need email templates in multiple languages with auto-detection.", status: "pending", category: "feature_request", senderName: "Kai Nakamura", senderEmail: "knakamura@global.co.jp", createdAt: new Date("2026-07-02T08:00:00Z") },
  { subject: "Time tracking per ticket", body: "We bill clients by the hour. Need the ability to log time spent on each ticket for accurate invoicing.", status: "open", category: "feature_request", senderName: "Rachel Simmons", senderEmail: "rsimmons@timebill.com", createdAt: new Date("2026-07-04T14:45:00Z") },
  { subject: "Keyboard shortcuts for common actions", body: "Power users want keyboard shortcuts: R for reply, A for assign, C for close, N for next ticket, etc.", status: "closed", category: "feature_request", senderName: "Dennis Graham", senderEmail: "dgraham@poweruser.dev", createdAt: new Date("2026-06-20T09:00:00Z") },
  { subject: "AI-suggested ticket categories", body: "Use AI to automatically suggest a category when a new ticket comes in, based on subject and body content.", status: "open", category: "feature_request", senderName: "Tanya Roberts", senderEmail: "troberts@aiops.tech", createdAt: new Date("2026-07-05T10:30:00Z") },
  { subject: "Collision detection – show when another agent is viewing", body: "Need to see when another agent is already viewing/replying to the same ticket to avoid duplicate responses.", status: "open", category: "feature_request", senderName: "Brandon Lee", senderEmail: "blee@multiagent.com", createdAt: new Date("2026-07-04T11:15:00Z") },
  { subject: "Scheduled ticket follow-ups / snooze", body: "Ability to snooze a ticket and have it re-appear in my queue at a specified future date/time.", status: "pending", category: "feature_request", senderName: "Jessica Reed", senderEmail: "jreed@followup.co", createdAt: new Date("2026-07-01T16:00:00Z") },
  { subject: "Reporting dashboard with charts and KPIs", body: "Need a dashboard showing: tickets by status, avg response time, resolution time trends, agent performance.", status: "open", category: "feature_request", senderName: "Omar Hassan", senderEmail: "ohassan@metrics.io", createdAt: new Date("2026-07-05T07:15:00Z") },

  // --- GENERAL (20 tickets) ---
  { subject: "How do I add a new team member?", body: "I'm the account admin and need to add 3 new agents to our team. Can't find the option in settings.", status: "resolved", category: "general", senderName: "Amanda Fisher", senderEmail: "afisher@teamlead.com", createdAt: new Date("2026-07-04T09:30:00Z") },
  { subject: "What are your support hours?", body: "We're in the APAC timezone (GMT+8). Are your support agents available during our business hours?", status: "closed", category: "general", senderName: "Wei Liu", senderEmail: "wliu@apacbiz.sg", createdAt: new Date("2026-07-03T02:00:00Z") },
  { subject: "Requesting product demo for our team", body: "We're a 50-person customer support team evaluating helpdesk solutions. Can we schedule a demo?", status: "pending", category: "general", senderName: "Katherine Powell", senderEmail: "kpowell@evalteam.com", createdAt: new Date("2026-07-03T11:30:00Z") },
  { subject: "Where can I find the API documentation?", body: "I'm a developer looking to integrate your platform with our CRM. Where is the API documentation?", status: "resolved", category: "general", senderName: "Eric Stone", senderEmail: "estone@integrations.dev", createdAt: new Date("2026-07-02T15:00:00Z") },
  { subject: "Account locked after too many login attempts", body: "I mistyped my password a few times and now my account is locked. How long until it unlocks?", status: "open", category: "general", senderName: "Diane Harper", senderEmail: "dharper@lockedout.com", createdAt: new Date("2026-07-05T05:30:00Z") },
  { subject: "GDPR data deletion request", body: "Under GDPR Article 17, I request the deletion of all personal data associated with my account (user ID: 8847).", status: "open", category: "general", senderName: "Franz Weber", senderEmail: "fweber@dataprivacy.eu", createdAt: new Date("2026-07-05T08:45:00Z") },
  { subject: "Can I use your platform for internal IT helpdesk?", body: "We want to use your platform for internal employee IT support tickets, not customer-facing. Is that a supported use case?", status: "resolved", category: "general", senderName: "Donna Mitchell", senderEmail: "dmitchell@internalsupport.org", createdAt: new Date("2026-07-01T14:30:00Z") },
  { subject: "Partnership inquiry – complementary SaaS product", body: "We build a live chat widget and think there's a great integration opportunity. Who should I speak with about partnerships?", status: "pending", category: "general", senderName: "Steve Rodriguez", senderEmail: "srodriguez@chatwidget.io", createdAt: new Date("2026-07-02T10:00:00Z") },
  { subject: "Training resources for new agents", body: "We just hired 5 new support agents. Are there training videos or a knowledge base to help them get started?", status: "resolved", category: "general", senderName: "Laura Bennett", senderEmail: "lbennett@onboarding.co", createdAt: new Date("2026-06-30T11:00:00Z") },
  { subject: "Compliance: SOC 2 Type II report available?", body: "Our security team requires a SOC 2 Type II report before we can approve your platform as a vendor. Do you have one?", status: "pending", category: "general", senderName: "Richard Evans", senderEmail: "revans@vendorapproval.com", createdAt: new Date("2026-07-03T13:00:00Z") },
  { subject: "Feedback on the new UI redesign", body: "The new interface looks clean but the ticket list is harder to scan. The old layout showed more info at a glance.", status: "closed", category: "general", senderName: "Nicole Ward", senderEmail: "nward@uxfeedback.com", createdAt: new Date("2026-06-25T15:00:00Z") },
  { subject: "How to set up email forwarding to create tickets?", body: "I want to forward support@ourcompany.com to your platform so emails automatically become tickets. How do I set this up?", status: "resolved", category: "general", senderName: "Chris Baker", senderEmail: "cbaker@emailsetup.com", createdAt: new Date("2026-07-01T09:00:00Z") },
  { subject: "Do you have a mobile app?", body: "Our agents are sometimes on the go. Is there a mobile app (iOS/Android) for managing tickets?", status: "closed", category: "general", senderName: "Stephanie Cox", senderEmail: "scox@mobilefirst.co", createdAt: new Date("2026-06-22T12:00:00Z") },
  { subject: "Uptime SLA for enterprise plan?", body: "What's your guaranteed uptime SLA on the enterprise plan? We need 99.95% minimum.", status: "pending", category: "general", senderName: "Gregory Barnes", senderEmail: "gbarnes@enterprise.biz", createdAt: new Date("2026-07-02T16:30:00Z") },
  { subject: "Request to join beta program", body: "I heard you have a beta program for upcoming features. How can I join? Happy to provide feedback.", status: "open", category: "general", senderName: "Michelle Turner", senderEmail: "mturner@betauser.com", createdAt: new Date("2026-07-04T12:00:00Z") },
  { subject: "Accessibility compliance – WCAG 2.1 AA", body: "Does your platform meet WCAG 2.1 AA standards? We're required to use accessible tools per company policy.", status: "pending", category: "general", senderName: "Thomas Green", senderEmail: "tgreen@a11y.org", createdAt: new Date("2026-07-03T08:30:00Z") },
  { subject: "Account transfer to new owner", body: "I'm leaving the company. Need to transfer account ownership to my colleague sarah@ourcompany.com.", status: "open", category: "general", senderName: "Peter Jackson", senderEmail: "pjackson@transition.co", createdAt: new Date("2026-07-04T17:30:00Z") },
  { subject: "Integration with Jira for bug escalation", body: "When a support ticket is identified as a bug, we want to auto-create a Jira issue. Is there a native integration?", status: "pending", category: "general", senderName: "Angela Price", senderEmail: "aprice@jirauser.com", createdAt: new Date("2026-07-02T14:15:00Z") },
  { subject: "Data residency – EU hosting option?", body: "We need our data hosted in the EU for regulatory reasons. Do you offer an EU-hosted instance?", status: "open", category: "general", senderName: "Martin Schmidt", senderEmail: "mschmidt@eudata.de", createdAt: new Date("2026-07-05T10:00:00Z") },
  { subject: "Thank you for the quick resolution last week!", body: "Just wanted to say thanks to agent Sarah M. who resolved my issue within 20 minutes. Excellent support!", status: "closed", category: "general", senderName: "Jenny Park", senderEmail: "jpark@happycustomer.com", createdAt: new Date("2026-06-29T16:00:00Z") },
];

const created = await prisma.ticket.createMany({ data: tickets });
console.log(`Seeded ${created.count} tickets`);

await pool.end();
process.exit(0);
